/* tslint:disable */
/* eslint-disable */
/**
 * Snack Hub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  LoginModel,
  RegisterClientRequest,
} from '../models/index';
import {
    LoginModelFromJSON,
    LoginModelToJSON,
    RegisterClientRequestFromJSON,
    RegisterClientRequestToJSON,
} from '../models/index';

export interface ApiAuthenticationSigninPostRequest {
    loginModel?: LoginModel;
}

export interface ApiAuthenticationSignupPostRequest {
    registerClientRequest?: Omit<RegisterClientRequest, 'notifications'|'isValid'>;
}

/**
 * 
 */
export class AuthenticationApi extends runtime.BaseAPI {

    /**
     * Authenticates a user
     */
    async apiAuthenticationSigninPostRaw(requestParameters: ApiAuthenticationSigninPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Authentication/signin`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginModelToJSON(requestParameters['loginModel']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Authenticates a user
     */
    async apiAuthenticationSigninPost(requestParameters: ApiAuthenticationSigninPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiAuthenticationSigninPostRaw(requestParameters, initOverrides);
    }

    /**
     * Registers a new user
     */
    async apiAuthenticationSignupPostRaw(requestParameters: ApiAuthenticationSignupPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Authentication/signup`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RegisterClientRequestToJSON(requestParameters['registerClientRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Registers a new user
     */
    async apiAuthenticationSignupPost(requestParameters: ApiAuthenticationSignupPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiAuthenticationSignupPostRaw(requestParameters, initOverrides);
    }

}
