/* tslint:disable */
/* eslint-disable */
/**
 * Snack Hub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PaymentStatusDto,
} from '../models/index';
import {
    PaymentStatusDtoFromJSON,
    PaymentStatusDtoToJSON,
} from '../models/index';

export interface ApiWebhookV1PaymentStatusPostRequest {
    paymentStatusDto?: PaymentStatusDto;
}

/**
 * 
 */
export class WebhookApi extends runtime.BaseAPI {

    /**
     */
    async apiWebhookV1PaymentStatusPostRaw(requestParameters: ApiWebhookV1PaymentStatusPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Webhook/v1/payment-status`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PaymentStatusDtoToJSON(requestParameters['paymentStatusDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiWebhookV1PaymentStatusPost(requestParameters: ApiWebhookV1PaymentStatusPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiWebhookV1PaymentStatusPostRaw(requestParameters, initOverrides);
    }

}
