/* tslint:disable */
/* eslint-disable */
/**
 * Snack Hub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CancelOrderRequest
 */
export interface CancelOrderRequest {
    /**
     * 
     * @type {string}
     * @memberof CancelOrderRequest
     */
    orderId?: string;
}

/**
 * Check if a given object implements the CancelOrderRequest interface.
 */
export function instanceOfCancelOrderRequest(value: object): value is CancelOrderRequest {
    return true;
}

export function CancelOrderRequestFromJSON(json: any): CancelOrderRequest {
    return CancelOrderRequestFromJSONTyped(json, false);
}

export function CancelOrderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CancelOrderRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'orderId': json['orderId'] == null ? undefined : json['orderId'],
    };
}

export function CancelOrderRequestToJSON(json: any): CancelOrderRequest {
    return CancelOrderRequestToJSONTyped(json, false);
}

export function CancelOrderRequestToJSONTyped(value?: CancelOrderRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'orderId': value['orderId'],
    };
}

