/* tslint:disable */
/* eslint-disable */
/**
 * Snack Hub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Notification } from './Notification';
import {
    NotificationFromJSON,
    NotificationFromJSONTyped,
    NotificationToJSON,
    NotificationToJSONTyped,
} from './Notification';

/**
 * 
 * @export
 * @interface CancelOrderResponse
 */
export interface CancelOrderResponse {
    /**
     * 
     * @type {Array<Notification>}
     * @memberof CancelOrderResponse
     */
    readonly notifications?: Array<Notification> | null;
    /**
     * 
     * @type {boolean}
     * @memberof CancelOrderResponse
     */
    readonly isValid?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof CancelOrderResponse
     */
    cancelledAt?: Date | null;
}

/**
 * Check if a given object implements the CancelOrderResponse interface.
 */
export function instanceOfCancelOrderResponse(value: object): value is CancelOrderResponse {
    return true;
}

export function CancelOrderResponseFromJSON(json: any): CancelOrderResponse {
    return CancelOrderResponseFromJSONTyped(json, false);
}

export function CancelOrderResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CancelOrderResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'notifications': json['notifications'] == null ? undefined : ((json['notifications'] as Array<any>).map(NotificationFromJSON)),
        'isValid': json['isValid'] == null ? undefined : json['isValid'],
        'cancelledAt': json['cancelledAt'] == null ? undefined : (new Date(json['cancelledAt'])),
    };
}

export function CancelOrderResponseToJSON(json: any): CancelOrderResponse {
    return CancelOrderResponseToJSONTyped(json, false);
}

export function CancelOrderResponseToJSONTyped(value?: Omit<CancelOrderResponse, 'notifications'|'isValid'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cancelledAt': value['cancelledAt'] == null ? undefined : ((value['cancelledAt'] as any).toISOString()),
    };
}

