/* tslint:disable */
/* eslint-disable */
/**
 * Snack Hub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CheckoutOrderRequest
 */
export interface CheckoutOrderRequest {
    /**
     * 
     * @type {string}
     * @memberof CheckoutOrderRequest
     */
    orderId?: string;
}

/**
 * Check if a given object implements the CheckoutOrderRequest interface.
 */
export function instanceOfCheckoutOrderRequest(value: object): value is CheckoutOrderRequest {
    return true;
}

export function CheckoutOrderRequestFromJSON(json: any): CheckoutOrderRequest {
    return CheckoutOrderRequestFromJSONTyped(json, false);
}

export function CheckoutOrderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckoutOrderRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'orderId': json['orderId'] == null ? undefined : json['orderId'],
    };
}

export function CheckoutOrderRequestToJSON(json: any): CheckoutOrderRequest {
    return CheckoutOrderRequestToJSONTyped(json, false);
}

export function CheckoutOrderRequestToJSONTyped(value?: CheckoutOrderRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'orderId': value['orderId'],
    };
}

