/* tslint:disable */
/* eslint-disable */
/**
 * Snack Hub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrderStatus } from './OrderStatus';
import {
    OrderStatusFromJSON,
    OrderStatusFromJSONTyped,
    OrderStatusToJSON,
    OrderStatusToJSONTyped,
} from './OrderStatus';
import type { Notification } from './Notification';
import {
    NotificationFromJSON,
    NotificationFromJSONTyped,
    NotificationToJSON,
    NotificationToJSONTyped,
} from './Notification';

/**
 * 
 * @export
 * @interface CheckPaymentStatusResponse
 */
export interface CheckPaymentStatusResponse {
    /**
     * 
     * @type {Array<Notification>}
     * @memberof CheckPaymentStatusResponse
     */
    readonly notifications?: Array<Notification> | null;
    /**
     * 
     * @type {boolean}
     * @memberof CheckPaymentStatusResponse
     */
    readonly isValid?: boolean;
    /**
     * 
     * @type {OrderStatus}
     * @memberof CheckPaymentStatusResponse
     */
    paymentStatus?: OrderStatus;
}



/**
 * Check if a given object implements the CheckPaymentStatusResponse interface.
 */
export function instanceOfCheckPaymentStatusResponse(value: object): value is CheckPaymentStatusResponse {
    return true;
}

export function CheckPaymentStatusResponseFromJSON(json: any): CheckPaymentStatusResponse {
    return CheckPaymentStatusResponseFromJSONTyped(json, false);
}

export function CheckPaymentStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckPaymentStatusResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'notifications': json['notifications'] == null ? undefined : ((json['notifications'] as Array<any>).map(NotificationFromJSON)),
        'isValid': json['isValid'] == null ? undefined : json['isValid'],
        'paymentStatus': json['paymentStatus'] == null ? undefined : OrderStatusFromJSON(json['paymentStatus']),
    };
}

export function CheckPaymentStatusResponseToJSON(json: any): CheckPaymentStatusResponse {
    return CheckPaymentStatusResponseToJSONTyped(json, false);
}

export function CheckPaymentStatusResponseToJSONTyped(value?: Omit<CheckPaymentStatusResponse, 'notifications'|'isValid'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'paymentStatus': OrderStatusToJSON(value['paymentStatus']),
    };
}

