/* tslint:disable */
/* eslint-disable */
/**
 * Snack Hub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Notification } from './Notification';
import {
    NotificationFromJSON,
    NotificationFromJSONTyped,
    NotificationToJSON,
    NotificationToJSONTyped,
} from './Notification';

/**
 * 
 * @export
 * @interface CheckoutOrderResponse
 */
export interface CheckoutOrderResponse {
    /**
     * 
     * @type {Array<Notification>}
     * @memberof CheckoutOrderResponse
     */
    readonly notifications?: Array<Notification> | null;
    /**
     * 
     * @type {boolean}
     * @memberof CheckoutOrderResponse
     */
    readonly isValid?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CheckoutOrderResponse
     */
    transactionId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CheckoutOrderResponse
     */
    paymentStatus?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof CheckoutOrderResponse
     */
    processedAt?: Date | null;
}

/**
 * Check if a given object implements the CheckoutOrderResponse interface.
 */
export function instanceOfCheckoutOrderResponse(value: object): value is CheckoutOrderResponse {
    return true;
}

export function CheckoutOrderResponseFromJSON(json: any): CheckoutOrderResponse {
    return CheckoutOrderResponseFromJSONTyped(json, false);
}

export function CheckoutOrderResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckoutOrderResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'notifications': json['notifications'] == null ? undefined : ((json['notifications'] as Array<any>).map(NotificationFromJSON)),
        'isValid': json['isValid'] == null ? undefined : json['isValid'],
        'transactionId': json['transactionId'] == null ? undefined : json['transactionId'],
        'paymentStatus': json['paymentStatus'] == null ? undefined : json['paymentStatus'],
        'processedAt': json['processedAt'] == null ? undefined : (new Date(json['processedAt'])),
    };
}

export function CheckoutOrderResponseToJSON(json: any): CheckoutOrderResponse {
    return CheckoutOrderResponseToJSONTyped(json, false);
}

export function CheckoutOrderResponseToJSONTyped(value?: Omit<CheckoutOrderResponse, 'notifications'|'isValid'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'transactionId': value['transactionId'],
        'paymentStatus': value['paymentStatus'],
        'processedAt': value['processedAt'] == null ? undefined : ((value['processedAt'] as any).toISOString()),
    };
}

