/* tslint:disable */
/* eslint-disable */
/**
 * Snack Hub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Notification } from './Notification';
import {
    NotificationFromJSON,
    NotificationFromJSONTyped,
    NotificationToJSON,
    NotificationToJSONTyped,
} from './Notification';

/**
 * 
 * @export
 * @interface ConfirmOrderResponse
 */
export interface ConfirmOrderResponse {
    /**
     * 
     * @type {Array<Notification>}
     * @memberof ConfirmOrderResponse
     */
    readonly notifications?: Array<Notification> | null;
    /**
     * 
     * @type {boolean}
     * @memberof ConfirmOrderResponse
     */
    readonly isValid?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ConfirmOrderResponse
     */
    orderId?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ConfirmOrderResponse
     */
    total?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof ConfirmOrderResponse
     */
    createdAt?: Date | null;
}

/**
 * Check if a given object implements the ConfirmOrderResponse interface.
 */
export function instanceOfConfirmOrderResponse(value: object): value is ConfirmOrderResponse {
    return true;
}

export function ConfirmOrderResponseFromJSON(json: any): ConfirmOrderResponse {
    return ConfirmOrderResponseFromJSONTyped(json, false);
}

export function ConfirmOrderResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfirmOrderResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'notifications': json['notifications'] == null ? undefined : ((json['notifications'] as Array<any>).map(NotificationFromJSON)),
        'isValid': json['isValid'] == null ? undefined : json['isValid'],
        'orderId': json['orderId'] == null ? undefined : json['orderId'],
        'total': json['total'] == null ? undefined : json['total'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function ConfirmOrderResponseToJSON(json: any): ConfirmOrderResponse {
    return ConfirmOrderResponseToJSONTyped(json, false);
}

export function ConfirmOrderResponseToJSONTyped(value?: Omit<ConfirmOrderResponse, 'notifications'|'isValid'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'orderId': value['orderId'],
        'total': value['total'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt'] as any).toISOString()),
    };
}

