/* tslint:disable */
/* eslint-disable */
/**
 * Snack Hub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CPF
 */
export interface CPF {
    /**
     * 
     * @type {string}
     * @memberof CPF
     */
    value?: string | null;
}

/**
 * Check if a given object implements the CPF interface.
 */
export function instanceOfCPF(value: object): value is CPF {
    return true;
}

export function CPFFromJSON(json: any): CPF {
    return CPFFromJSONTyped(json, false);
}

export function CPFFromJSONTyped(json: any, ignoreDiscriminator: boolean): CPF {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function CPFToJSON(json: any): CPF {
    return CPFToJSONTyped(json, false);
}

export function CPFToJSONTyped(value?: CPF | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'],
    };
}

