/* tslint:disable */
/* eslint-disable */
/**
 * Snack Hub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Category } from './Category';
import {
    CategoryFromJSON,
    CategoryFromJSONTyped,
    CategoryToJSON,
    CategoryToJSONTyped,
} from './Category';

/**
 * 
 * @export
 * @interface GetProductResponse
 */
export interface GetProductResponse {
    /**
     * 
     * @type {string}
     * @memberof GetProductResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof GetProductResponse
     */
    name?: string | null;
    /**
     * 
     * @type {Category}
     * @memberof GetProductResponse
     */
    category?: Category;
    /**
     * 
     * @type {number}
     * @memberof GetProductResponse
     */
    price?: number;
    /**
     * 
     * @type {string}
     * @memberof GetProductResponse
     */
    description?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetProductResponse
     */
    images?: Array<string> | null;
}



/**
 * Check if a given object implements the GetProductResponse interface.
 */
export function instanceOfGetProductResponse(value: object): value is GetProductResponse {
    return true;
}

export function GetProductResponseFromJSON(json: any): GetProductResponse {
    return GetProductResponseFromJSONTyped(json, false);
}

export function GetProductResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetProductResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'category': json['category'] == null ? undefined : CategoryFromJSON(json['category']),
        'price': json['price'] == null ? undefined : json['price'],
        'description': json['description'] == null ? undefined : json['description'],
        'images': json['images'] == null ? undefined : json['images'],
    };
}

export function GetProductResponseToJSON(json: any): GetProductResponse {
    return GetProductResponseToJSONTyped(json, false);
}

export function GetProductResponseToJSONTyped(value?: GetProductResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'category': CategoryToJSON(value['category']),
        'price': value['price'],
        'description': value['description'],
        'images': value['images'],
    };
}

