/* tslint:disable */
/* eslint-disable */
/**
 * Snack Hub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginModel
 */
export interface LoginModel {
    /**
     * 
     * @type {string}
     * @memberof LoginModel
     */
    cpf?: string | null;
}

/**
 * Check if a given object implements the LoginModel interface.
 */
export function instanceOfLoginModel(value: object): value is LoginModel {
    return true;
}

export function LoginModelFromJSON(json: any): LoginModel {
    return LoginModelFromJSONTyped(json, false);
}

export function LoginModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginModel {
    if (json == null) {
        return json;
    }
    return {
        
        'cpf': json['cpf'] == null ? undefined : json['cpf'],
    };
}

export function LoginModelToJSON(json: any): LoginModel {
    return LoginModelToJSONTyped(json, false);
}

export function LoginModelToJSONTyped(value?: LoginModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cpf': value['cpf'],
    };
}

