/* tslint:disable */
/* eslint-disable */
/**
 * Snack Hub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ManageProductResponse
 */
export interface ManageProductResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof ManageProductResponse
     */
    notifications?: Array<string> | null;
    /**
     * 
     * @type {boolean}
     * @memberof ManageProductResponse
     */
    isValid?: boolean;
}

/**
 * Check if a given object implements the ManageProductResponse interface.
 */
export function instanceOfManageProductResponse(value: object): value is ManageProductResponse {
    return true;
}

export function ManageProductResponseFromJSON(json: any): ManageProductResponse {
    return ManageProductResponseFromJSONTyped(json, false);
}

export function ManageProductResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManageProductResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'notifications': json['notifications'] == null ? undefined : json['notifications'],
        'isValid': json['isValid'] == null ? undefined : json['isValid'],
    };
}

export function ManageProductResponseToJSON(json: any): ManageProductResponse {
    return ManageProductResponseToJSONTyped(json, false);
}

export function ManageProductResponseToJSONTyped(value?: ManageProductResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'notifications': value['notifications'],
        'isValid': value['isValid'],
    };
}

