/* tslint:disable */
/* eslint-disable */
/**
 * Snack Hub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaymentStatusDto
 */
export interface PaymentStatusDto {
    /**
     * 
     * @type {string}
     * @memberof PaymentStatusDto
     */
    paymentId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentStatusDto
     */
    newStatus?: string | null;
}

/**
 * Check if a given object implements the PaymentStatusDto interface.
 */
export function instanceOfPaymentStatusDto(value: object): value is PaymentStatusDto {
    return true;
}

export function PaymentStatusDtoFromJSON(json: any): PaymentStatusDto {
    return PaymentStatusDtoFromJSONTyped(json, false);
}

export function PaymentStatusDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentStatusDto {
    if (json == null) {
        return json;
    }
    return {
        
        'paymentId': json['paymentId'] == null ? undefined : json['paymentId'],
        'newStatus': json['newStatus'] == null ? undefined : json['newStatus'],
    };
}

export function PaymentStatusDtoToJSON(json: any): PaymentStatusDto {
    return PaymentStatusDtoToJSONTyped(json, false);
}

export function PaymentStatusDtoToJSONTyped(value?: PaymentStatusDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'paymentId': value['paymentId'],
        'newStatus': value['newStatus'],
    };
}

