/* tslint:disable */
/* eslint-disable */
/**
 * Snack Hub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Notification } from './Notification';
import {
    NotificationFromJSON,
    NotificationFromJSONTyped,
    NotificationToJSON,
    NotificationToJSONTyped,
} from './Notification';

/**
 * 
 * @export
 * @interface RegisterClientRequest
 */
export interface RegisterClientRequest {
    /**
     * 
     * @type {Array<Notification>}
     * @memberof RegisterClientRequest
     */
    readonly notifications?: Array<Notification> | null;
    /**
     * 
     * @type {boolean}
     * @memberof RegisterClientRequest
     */
    readonly isValid?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RegisterClientRequest
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RegisterClientRequest
     */
    cpf?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RegisterClientRequest
     */
    email?: string | null;
}

/**
 * Check if a given object implements the RegisterClientRequest interface.
 */
export function instanceOfRegisterClientRequest(value: object): value is RegisterClientRequest {
    return true;
}

export function RegisterClientRequestFromJSON(json: any): RegisterClientRequest {
    return RegisterClientRequestFromJSONTyped(json, false);
}

export function RegisterClientRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterClientRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'notifications': json['notifications'] == null ? undefined : ((json['notifications'] as Array<any>).map(NotificationFromJSON)),
        'isValid': json['isValid'] == null ? undefined : json['isValid'],
        'name': json['name'] == null ? undefined : json['name'],
        'cpf': json['cpf'] == null ? undefined : json['cpf'],
        'email': json['email'] == null ? undefined : json['email'],
    };
}

export function RegisterClientRequestToJSON(json: any): RegisterClientRequest {
    return RegisterClientRequestToJSONTyped(json, false);
}

export function RegisterClientRequestToJSONTyped(value?: Omit<RegisterClientRequest, 'notifications'|'isValid'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'cpf': value['cpf'],
        'email': value['email'],
    };
}

