/* tslint:disable */
/* eslint-disable */
/**
 * Snack Hub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Notification } from './Notification';
import {
    NotificationFromJSON,
    NotificationFromJSONTyped,
    NotificationToJSON,
    NotificationToJSONTyped,
} from './Notification';

/**
 * 
 * @export
 * @interface UpdateKitchenOrderStatusResponse
 */
export interface UpdateKitchenOrderStatusResponse {
    /**
     * 
     * @type {Array<Notification>}
     * @memberof UpdateKitchenOrderStatusResponse
     */
    readonly notifications?: Array<Notification> | null;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateKitchenOrderStatusResponse
     */
    readonly isValid?: boolean;
}

/**
 * Check if a given object implements the UpdateKitchenOrderStatusResponse interface.
 */
export function instanceOfUpdateKitchenOrderStatusResponse(value: object): value is UpdateKitchenOrderStatusResponse {
    return true;
}

export function UpdateKitchenOrderStatusResponseFromJSON(json: any): UpdateKitchenOrderStatusResponse {
    return UpdateKitchenOrderStatusResponseFromJSONTyped(json, false);
}

export function UpdateKitchenOrderStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateKitchenOrderStatusResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'notifications': json['notifications'] == null ? undefined : ((json['notifications'] as Array<any>).map(NotificationFromJSON)),
        'isValid': json['isValid'] == null ? undefined : json['isValid'],
    };
}

export function UpdateKitchenOrderStatusResponseToJSON(json: any): UpdateKitchenOrderStatusResponse {
    return UpdateKitchenOrderStatusResponseToJSONTyped(json, false);
}

export function UpdateKitchenOrderStatusResponseToJSONTyped(value?: Omit<UpdateKitchenOrderStatusResponse, 'notifications'|'isValid'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

