/* tslint:disable */
/* eslint-disable */
/**
 * Snack Hub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateKitchenOrderStatusRequest
 */
export interface UpdateKitchenOrderStatusRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateKitchenOrderStatusRequest
     */
    orderId?: string;
}

/**
 * Check if a given object implements the UpdateKitchenOrderStatusRequest interface.
 */
export function instanceOfUpdateKitchenOrderStatusRequest(value: object): value is UpdateKitchenOrderStatusRequest {
    return true;
}

export function UpdateKitchenOrderStatusRequestFromJSON(json: any): UpdateKitchenOrderStatusRequest {
    return UpdateKitchenOrderStatusRequestFromJSONTyped(json, false);
}

export function UpdateKitchenOrderStatusRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateKitchenOrderStatusRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'orderId': json['orderId'] == null ? undefined : json['orderId'],
    };
}

export function UpdateKitchenOrderStatusRequestToJSON(json: any): UpdateKitchenOrderStatusRequest {
    return UpdateKitchenOrderStatusRequestToJSONTyped(json, false);
}

export function UpdateKitchenOrderStatusRequestToJSONTyped(value?: UpdateKitchenOrderStatusRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'orderId': value['orderId'],
    };
}

