/* tslint:disable */
/* eslint-disable */
/**
 * Snack Hub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Notification } from './Notification';
import {
    NotificationFromJSON,
    NotificationFromJSONTyped,
    NotificationToJSON,
    NotificationToJSONTyped,
} from './Notification';

/**
 * 
 * @export
 * @interface UpdateOrderStatusResponse
 */
export interface UpdateOrderStatusResponse {
    /**
     * 
     * @type {Array<Notification>}
     * @memberof UpdateOrderStatusResponse
     */
    readonly notifications?: Array<Notification> | null;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateOrderStatusResponse
     */
    readonly isValid?: boolean;
}

/**
 * Check if a given object implements the UpdateOrderStatusResponse interface.
 */
export function instanceOfUpdateOrderStatusResponse(value: object): value is UpdateOrderStatusResponse {
    return true;
}

export function UpdateOrderStatusResponseFromJSON(json: any): UpdateOrderStatusResponse {
    return UpdateOrderStatusResponseFromJSONTyped(json, false);
}

export function UpdateOrderStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateOrderStatusResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'notifications': json['notifications'] == null ? undefined : ((json['notifications'] as Array<any>).map(NotificationFromJSON)),
        'isValid': json['isValid'] == null ? undefined : json['isValid'],
    };
}

export function UpdateOrderStatusResponseToJSON(json: any): UpdateOrderStatusResponse {
    return UpdateOrderStatusResponseToJSONTyped(json, false);
}

export function UpdateOrderStatusResponseToJSONTyped(value?: Omit<UpdateOrderStatusResponse, 'notifications'|'isValid'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

