/* tslint:disable */
/* eslint-disable */
/**
 * IdentityService.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  NotifyOrderUpdateStatusRequest,
} from '../models/index';
import {
    NotifyOrderUpdateStatusRequestFromJSON,
    NotifyOrderUpdateStatusRequestToJSON,
} from '../models/index';

export interface ApiEmailV1NotifyPostRequest {
    notifyOrderUpdateStatusRequest?: NotifyOrderUpdateStatusRequest;
}

/**
 * 
 */
export class EmailApi extends runtime.BaseAPI {

    /**
     */
    async apiEmailV1NotifyPostRaw(requestParameters: ApiEmailV1NotifyPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/Email/v1/notify`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NotifyOrderUpdateStatusRequestToJSON(requestParameters['notifyOrderUpdateStatusRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiEmailV1NotifyPost(requestParameters: ApiEmailV1NotifyPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiEmailV1NotifyPostRaw(requestParameters, initOverrides);
    }

}
