/* tslint:disable */
/* eslint-disable */
/**
 * IdentityService.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  LoginModel,
  RegisterClientRequest,
} from '../models/index';
import {
    LoginModelFromJSON,
    LoginModelToJSON,
    RegisterClientRequestFromJSON,
    RegisterClientRequestToJSON,
} from '../models/index';

export interface ApiAuthenticationV1SigninPostRequest {
    loginModel?: LoginModel;
}

export interface ApiAuthenticationV1SignupPostRequest {
    registerClientRequest?: Omit<RegisterClientRequest, 'notifications'|'isValid'>;
}

/**
 * 
 */
export class AuthenticationApi extends runtime.BaseAPI {

    /**
     */
    async apiAuthenticationV1SigninPostRaw(requestParameters: ApiAuthenticationV1SigninPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/Authentication/v1/signin`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginModelToJSON(requestParameters['loginModel']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiAuthenticationV1SigninPost(requestParameters: ApiAuthenticationV1SigninPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiAuthenticationV1SigninPostRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiAuthenticationV1SignupPostRaw(requestParameters: ApiAuthenticationV1SignupPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/Authentication/v1/signup`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RegisterClientRequestToJSON(requestParameters['registerClientRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiAuthenticationV1SignupPost(requestParameters: ApiAuthenticationV1SignupPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiAuthenticationV1SignupPostRaw(requestParameters, initOverrides);
    }

}
