/* tslint:disable */
/* eslint-disable */
/**
 * IdentityService.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NotifyOrderUpdateStatusRequest
 */
export interface NotifyOrderUpdateStatusRequest {
    /**
     * 
     * @type {string}
     * @memberof NotifyOrderUpdateStatusRequest
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NotifyOrderUpdateStatusRequest
     */
    orderId?: string;
    /**
     * 
     * @type {string}
     * @memberof NotifyOrderUpdateStatusRequest
     */
    orderStatus?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NotifyOrderUpdateStatusRequest
     */
    packageUri?: string | null;
}

/**
 * Check if a given object implements the NotifyOrderUpdateStatusRequest interface.
 */
export function instanceOfNotifyOrderUpdateStatusRequest(value: object): value is NotifyOrderUpdateStatusRequest {
    return true;
}

export function NotifyOrderUpdateStatusRequestFromJSON(json: any): NotifyOrderUpdateStatusRequest {
    return NotifyOrderUpdateStatusRequestFromJSONTyped(json, false);
}

export function NotifyOrderUpdateStatusRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotifyOrderUpdateStatusRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'orderId': json['orderId'] == null ? undefined : json['orderId'],
        'orderStatus': json['orderStatus'] == null ? undefined : json['orderStatus'],
        'packageUri': json['packageUri'] == null ? undefined : json['packageUri'],
    };
}

export function NotifyOrderUpdateStatusRequestToJSON(json: any): NotifyOrderUpdateStatusRequest {
    return NotifyOrderUpdateStatusRequestToJSONTyped(json, false);
}

export function NotifyOrderUpdateStatusRequestToJSONTyped(value?: NotifyOrderUpdateStatusRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'orderId': value['orderId'],
        'orderStatus': value['orderStatus'],
        'packageUri': value['packageUri'],
    };
}

