/* tslint:disable */
/* eslint-disable */
/**
 * IdentityService.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Notification } from './Notification';
import {
    NotificationFromJSON,
    NotificationFromJSONTyped,
    NotificationToJSON,
    NotificationToJSONTyped,
} from './Notification';

/**
 * 
 * @export
 * @interface RegisterClientResponse
 */
export interface RegisterClientResponse {
    /**
     * 
     * @type {Array<Notification>}
     * @memberof RegisterClientResponse
     */
    readonly notifications?: Array<Notification> | null;
    /**
     * 
     * @type {boolean}
     * @memberof RegisterClientResponse
     */
    readonly isValid?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RegisterClientResponse
     */
    id?: string | null;
}

/**
 * Check if a given object implements the RegisterClientResponse interface.
 */
export function instanceOfRegisterClientResponse(value: object): value is RegisterClientResponse {
    return true;
}

export function RegisterClientResponseFromJSON(json: any): RegisterClientResponse {
    return RegisterClientResponseFromJSONTyped(json, false);
}

export function RegisterClientResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterClientResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'notifications': json['notifications'] == null ? undefined : ((json['notifications'] as Array<any>).map(NotificationFromJSON)),
        'isValid': json['isValid'] == null ? undefined : json['isValid'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function RegisterClientResponseToJSON(json: any): RegisterClientResponse {
    return RegisterClientResponseToJSONTyped(json, false);
}

export function RegisterClientResponseToJSONTyped(value?: Omit<RegisterClientResponse, 'notifications'|'isValid'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

