/* tslint:disable */
/* eslint-disable */
/**
 * IdentityService.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Notification } from './Notification';
import {
    NotificationFromJSON,
    NotificationFromJSONTyped,
    NotificationToJSON,
    NotificationToJSONTyped,
} from './Notification';

/**
 * 
 * @export
 * @interface SignInResponse
 */
export interface SignInResponse {
    /**
     * 
     * @type {Array<Notification>}
     * @memberof SignInResponse
     */
    readonly notifications?: Array<Notification> | null;
    /**
     * 
     * @type {boolean}
     * @memberof SignInResponse
     */
    readonly isValid?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SignInResponse
     */
    idToken?: string | null;
}

/**
 * Check if a given object implements the SignInResponse interface.
 */
export function instanceOfSignInResponse(value: object): value is SignInResponse {
    return true;
}

export function SignInResponseFromJSON(json: any): SignInResponse {
    return SignInResponseFromJSONTyped(json, false);
}

export function SignInResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignInResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'notifications': json['notifications'] == null ? undefined : ((json['notifications'] as Array<any>).map(NotificationFromJSON)),
        'isValid': json['isValid'] == null ? undefined : json['isValid'],
        'idToken': json['idToken'] == null ? undefined : json['idToken'],
    };
}

export function SignInResponseToJSON(json: any): SignInResponse {
    return SignInResponseToJSONTyped(json, false);
}

export function SignInResponseToJSONTyped(value?: Omit<SignInResponse, 'notifications'|'isValid'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'idToken': value['idToken'],
    };
}

