/* tslint:disable */
/* eslint-disable */
/**
 * IdentityService.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Cpf } from './Cpf';
import {
    CpfFromJSON,
    CpfFromJSONTyped,
    CpfToJSON,
    CpfToJSONTyped,
} from './Cpf';

/**
 * 
 * @export
 * @interface GetClientResponse
 */
export interface GetClientResponse {
    /**
     * 
     * @type {string}
     * @memberof GetClientResponse
     */
    name?: string | null;
    /**
     * 
     * @type {Cpf}
     * @memberof GetClientResponse
     */
    cpf?: Cpf;
    /**
     * 
     * @type {string}
     * @memberof GetClientResponse
     */
    readonly email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetClientResponse
     */
    readonly id?: string;
}

/**
 * Check if a given object implements the GetClientResponse interface.
 */
export function instanceOfGetClientResponse(value: object): value is GetClientResponse {
    return true;
}

export function GetClientResponseFromJSON(json: any): GetClientResponse {
    return GetClientResponseFromJSONTyped(json, false);
}

export function GetClientResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetClientResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'cpf': json['cpf'] == null ? undefined : CpfFromJSON(json['cpf']),
        'email': json['email'] == null ? undefined : json['email'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function GetClientResponseToJSON(json: any): GetClientResponse {
    return GetClientResponseToJSONTyped(json, false);
}

export function GetClientResponseToJSONTyped(value?: Omit<GetClientResponse, 'email'|'id'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'cpf': CpfToJSON(value['cpf']),
    };
}

