/* tslint:disable */
/* eslint-disable */
/**
 * FrameUp.OrderService.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PackageItemResponse
 */
export interface PackageItemResponse {
    /**
     * 
     * @type {string}
     * @memberof PackageItemResponse
     */
    fileName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PackageItemResponse
     */
    uri?: string | null;
}

/**
 * Check if a given object implements the PackageItemResponse interface.
 */
export function instanceOfPackageItemResponse(value: object): value is PackageItemResponse {
    return true;
}

export function PackageItemResponseFromJSON(json: any): PackageItemResponse {
    return PackageItemResponseFromJSONTyped(json, false);
}

export function PackageItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PackageItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'fileName': json['fileName'] == null ? undefined : json['fileName'],
        'uri': json['uri'] == null ? undefined : json['uri'],
    };
}

export function PackageItemResponseToJSON(json: any): PackageItemResponse {
    return PackageItemResponseToJSONTyped(json, false);
}

export function PackageItemResponseToJSONTyped(value?: PackageItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fileName': value['fileName'],
        'uri': value['uri'],
    };
}

