/* tslint:disable */
/* eslint-disable */
/**
 * FrameUp.OrderService.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ResolutionTypes = {
    QuadHd: 'QuadHD',
    FullHd: 'FullHD',
    Hd: 'HD',
    Sd: 'SD'
} as const;
export type ResolutionTypes = typeof ResolutionTypes[keyof typeof ResolutionTypes];


export function instanceOfResolutionTypes(value: any): boolean {
    for (const key in ResolutionTypes) {
        if (Object.prototype.hasOwnProperty.call(ResolutionTypes, key)) {
            if (ResolutionTypes[key as keyof typeof ResolutionTypes] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ResolutionTypesFromJSON(json: any): ResolutionTypes {
    return ResolutionTypesFromJSONTyped(json, false);
}

export function ResolutionTypesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResolutionTypes {
    return json as ResolutionTypes;
}

export function ResolutionTypesToJSON(value?: ResolutionTypes | null): any {
    return value as any;
}

export function ResolutionTypesToJSONTyped(value: any, ignoreDiscriminator: boolean): ResolutionTypes {
    return value as ResolutionTypes;
}

