/* tslint:disable */
/* eslint-disable */
/**
 * FrameUp.OrderService.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Notification } from './Notification';
import {
    NotificationFromJSON,
    NotificationFromJSONTyped,
    NotificationToJSON,
    NotificationToJSONTyped,
} from './Notification';

/**
 * 
 * @export
 * @interface UpdateProcessingOrderResponse
 */
export interface UpdateProcessingOrderResponse {
    /**
     * 
     * @type {Array<Notification>}
     * @memberof UpdateProcessingOrderResponse
     */
    readonly notifications?: Array<Notification> | null;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateProcessingOrderResponse
     */
    readonly isValid?: boolean;
}

/**
 * Check if a given object implements the UpdateProcessingOrderResponse interface.
 */
export function instanceOfUpdateProcessingOrderResponse(value: object): value is UpdateProcessingOrderResponse {
    return true;
}

export function UpdateProcessingOrderResponseFromJSON(json: any): UpdateProcessingOrderResponse {
    return UpdateProcessingOrderResponseFromJSONTyped(json, false);
}

export function UpdateProcessingOrderResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateProcessingOrderResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'notifications': json['notifications'] == null ? undefined : ((json['notifications'] as Array<any>).map(NotificationFromJSON)),
        'isValid': json['isValid'] == null ? undefined : json['isValid'],
    };
}

export function UpdateProcessingOrderResponseToJSON(json: any): UpdateProcessingOrderResponse {
    return UpdateProcessingOrderResponseToJSONTyped(json, false);
}

export function UpdateProcessingOrderResponseToJSONTyped(value?: Omit<UpdateProcessingOrderResponse, 'notifications'|'isValid'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

