/* tslint:disable */
/* eslint-disable */
/**
 * FrameUp.OrderService.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UpdatePackageItemRequest } from './UpdatePackageItemRequest';
import {
    UpdatePackageItemRequestFromJSON,
    UpdatePackageItemRequestFromJSONTyped,
    UpdatePackageItemRequestToJSON,
    UpdatePackageItemRequestToJSONTyped,
} from './UpdatePackageItemRequest';
import type { ProcessingStatus } from './ProcessingStatus';
import {
    ProcessingStatusFromJSON,
    ProcessingStatusFromJSONTyped,
    ProcessingStatusToJSON,
    ProcessingStatusToJSONTyped,
} from './ProcessingStatus';

/**
 * 
 * @export
 * @interface UpdateProcessingOrderRequest
 */
export interface UpdateProcessingOrderRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateProcessingOrderRequest
     */
    orderId: string;
    /**
     * 
     * @type {ProcessingStatus}
     * @memberof UpdateProcessingOrderRequest
     */
    status: ProcessingStatus;
    /**
     * 
     * @type {Array<UpdatePackageItemRequest>}
     * @memberof UpdateProcessingOrderRequest
     */
    packages?: Array<UpdatePackageItemRequest> | null;
}



/**
 * Check if a given object implements the UpdateProcessingOrderRequest interface.
 */
export function instanceOfUpdateProcessingOrderRequest(value: object): value is UpdateProcessingOrderRequest {
    if (!('orderId' in value) || value['orderId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function UpdateProcessingOrderRequestFromJSON(json: any): UpdateProcessingOrderRequest {
    return UpdateProcessingOrderRequestFromJSONTyped(json, false);
}

export function UpdateProcessingOrderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateProcessingOrderRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'orderId': json['orderId'],
        'status': ProcessingStatusFromJSON(json['status']),
        'packages': json['packages'] == null ? undefined : ((json['packages'] as Array<any>).map(UpdatePackageItemRequestFromJSON)),
    };
}

export function UpdateProcessingOrderRequestToJSON(json: any): UpdateProcessingOrderRequest {
    return UpdateProcessingOrderRequestToJSONTyped(json, false);
}

export function UpdateProcessingOrderRequestToJSONTyped(value?: UpdateProcessingOrderRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'orderId': value['orderId'],
        'status': ProcessingStatusToJSON(value['status']),
        'packages': value['packages'] == null ? undefined : ((value['packages'] as Array<any>).map(UpdatePackageItemRequestToJSON)),
    };
}

