/* tslint:disable */
/* eslint-disable */
/**
 * FrameUp.OrderService.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VideoMetadataResponse
 */
export interface VideoMetadataResponse {
    /**
     * 
     * @type {string}
     * @memberof VideoMetadataResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof VideoMetadataResponse
     */
    name: string | null;
    /**
     * 
     * @type {string}
     * @memberof VideoMetadataResponse
     */
    contentType: string | null;
    /**
     * 
     * @type {number}
     * @memberof VideoMetadataResponse
     */
    size?: number;
}

/**
 * Check if a given object implements the VideoMetadataResponse interface.
 */
export function instanceOfVideoMetadataResponse(value: object): value is VideoMetadataResponse {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('contentType' in value) || value['contentType'] === undefined) return false;
    return true;
}

export function VideoMetadataResponseFromJSON(json: any): VideoMetadataResponse {
    return VideoMetadataResponseFromJSONTyped(json, false);
}

export function VideoMetadataResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoMetadataResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'contentType': json['contentType'],
        'size': json['size'] == null ? undefined : json['size'],
    };
}

export function VideoMetadataResponseToJSON(json: any): VideoMetadataResponse {
    return VideoMetadataResponseToJSONTyped(json, false);
}

export function VideoMetadataResponseToJSONTyped(value?: VideoMetadataResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'contentType': value['contentType'],
        'size': value['size'],
    };
}

